retrieveUnpackaged/objects/Candidate_Application__c.object
<CustomObject>
    <fields>
        <fullName>First_Line_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Line Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Candidate_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intended_Track__c</fullName>
        <label>Intended Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Second_Line_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Second Line Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Candidate_Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Candidate Application</label>
    <nameField>
        <displayFormat>TQBR-{00000000}</displayFormat>
        <label>Candidate Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Question_Response__c.object
<CustomObject>
    <fields>
        <fullName>Candidate_Application__c</fullName>
        <label>Candidate Application</label>
        <referenceTo>Candidate_Application__c</referenceTo>
        <relationshipName>Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question text.</description>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Questions</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{000000}</displayFormat>
        <label>Question Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/TQBRequestHandler_Test.cls
@isTest(SeeAllData=true)
public class TQBRequestHandler_Test {

    public static string TEST_TRACK = 'Development';
    //Candidate_Application__c
    @isTest
    public static void testInsertQuestionsToRequest(){
        // Insert a new request.
        Profile p = [select id, name from profile where name = 'Forms Profile'];                
        User u = new User(FirstName='test', LastName='User', profileID=p.id, Username='test@userdomain.abc', 
                    email='test@userdomain.abc', Alias='testU', CommunityNickname='testU', TimeZoneSidKey= 'America/Los_Angeles',
                    LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
        insert u;
        
        Candidate_Application__c request = new Candidate_Application__c();
        request.Intended_Track__c = TEST_TRACK;
        request.First_Line_Supervisor__c = u.Id;
        request.Second_Line_Supervisor__c = u.Id;
        request.RecordTypeId = '012r00000005DW1AAM';
        insert request;
        
        System.debug('Status ' + request.Id + ' & Status '+ request.Intended_Track__c);        
        
        TQBRequestHandler.addRelatedQuestions(new List<Candidate_Application__c>{request});
        // Validate if questoin responses have been updated with relavent questions.
		List<Question_Response__c> newRecords = [Select Id,Question__c from Question_Response__c where Candidate_Application__r.Id =:request.Id];
        List<Questions__c> relatedQuestions = [Select id,Question__c from Questions__c where Track__c =:TEST_TRACK];
        System.assertEquals(newRecords.size(),relatedQuestions.size());
    }
}