retrieveUnpackaged/objects/Forms__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <description>BAP Provisioning</description>
        <label>First/Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>BAP Provisioning</description>
        <label>Quantity</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Form</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/FormsPageController.cls
public class FormsPageController {

    public id selectedRTID {get;set;}
    public string selectedRTName {get;set;}
    public Forms__c form {get;set;}
    
    public boolean authenticated {get;set;}
    private map<string, string> params;
    public List<RecordType> getFormRTs(){
        return [select id, Name from RecordType where sObjectType = 'Forms__c']; 
    }
    
    public FormsPageController(){
        params = ApexPages.currentPage().getParameters();

    }
    
    public void onLoad(){
        
		checkAuthenticated();        
    }
    
    public void checkAuthenticated(){
        authenticated = true;
        
        authenticated = params.get('authenticated') == '1' ? true : false;
    }
    
    public pageReference saveForm(){
        upsert form;
        return null;
    }
    public pageReference pickRT(){
        form = new Forms__c(RecordTypeID = selectedRTID,
                           	Name__c = 'Test Form',
                           	Quantity__c = 1);
        insert form;
        return null;
        //return new ApexPages.StandardController(form).edit();
    }
}