retrieveUnpackaged/objects/Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Name__c</fullName>
        <formula>Submission__r.Agency_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agency Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commenter_Name__c</fullName>
        <formula>Submission__r.Commenter_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commenter Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submission_Number__c</fullName>
        <formula>Submission__r.Submission_Number__c</formula>
        <label>Submission Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <label>Submission</label>
        <referenceTo>Submission__c</referenceTo>
        <relationshipLabel>Snippets</relationshipLabel>
        <relationshipName>Snippets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Topic</label>
        <referenceTo>Topic__c</referenceTo>
        <relationshipName>Substantive_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Snippet</label>
    <nameField>
        <displayFormat>SBC-{000000}</displayFormat>
        <label>Snippet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snippets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Name__c</fullName>
        <label>Agency Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commenter_Name__c</fullName>
        <label>Commenter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Letter_Type__c</fullName>
        <label>Submission Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unique Letter</fullName>
                </value>
                <value>
                    <fullName>Duplicate Letter</fullName>
                </value>
                <value>
                    <fullName>Similar Letter</fullName>
                </value>
                <value>
                    <fullName>Unique Submission</fullName>
                </value>
                <value>
                    <fullName>Duplicate Submission</fullName>
                </value>
                <value>
                    <fullName>Similar Submission</fullName>
                </value>
                <value>
                    <fullName>Public Hearing</fullName>
                </value>
                <value>
                    <fullName>Supporting Document (EPA)</fullName>
                </value>
                <value>
                    <fullName>Mass Mailing Campaign</fullName>
                </value>
                <value>
                    <fullName>Wrong docket</fullName>
                </value>
                <value>
                    <fullName>Modified Mass Mailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Number__c</fullName>
        <externalId>true</externalId>
        <label>Submission Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Topic</label>
        <referenceTo>Topic__c</referenceTo>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Submission ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Topic__c.object
<CustomObject>
    <label>Topic</label>
    <nameField>
        <label>Topic Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/TopicDownloadController.cls
public class TopicDownloadController {
	@AuraEnabled
    public static Map<String,Object> getAllSnippets(String topicId) {
        Map<String,Object> result = new Map<String,Object>();
        result.put('topic', [select Name,Topic_Number__c from Topic__c where id = :topicId]);
		result.put('snippets', [select Name,Submission__r.Commenter_Name__c,Submission__r.Letter_Type__c,Submission__r.Submission_Number__c,Submission__r.Agency_Name__c from Snippet__c where Topic__c = :topicId]);
        return result;
    }
}