retrieveUnpackaged/objects/TQB_Candidate_Package__c.object
<CustomObject>
    <description>Custom object that stores the Candidate&apos;s promotion package data and related fields.</description>
    <fields>
        <fullName>Candidate_Name__c</fullName>
        <description>Users first and last name for display on the Candidate Package</description>
        <formula>CreatedBy.FirstName &amp;&apos; &apos;  &amp; CreatedBy.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Users first and last name for display on the Candidate Package</inlineHelpText>
        <label>Candidate Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Candidates_1st_Line_Supervisor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Candidate&apos;s 1st Line Supervisor name.</description>
        <inlineHelpText>The Candidate&apos;s 1st Line Supervisor name.</inlineHelpText>
        <label>Candidates 1st Line Supervisor Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.DeveloperName</field>
                <operation>equals</operation>
                <value>X1st_Line_Supervisor_Role</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>TQB_Candidate_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Status Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Candidate Package Statuses</description>
        <inlineHelpText>Candidate Package Statuses</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Approved By 1st Line Supervisor</fullName>
                </value>
                <value>
                    <fullName>Approved By 2nd Line Supervisor</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TQB Candidate Package</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Candidate Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TQB_Candidate_Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/TQB1stLineSupervisorLPController.cls
public with sharing class TQB1stLineSupervisorLPController {
    
    @AuraEnabled
    public static List<TQB_Letter_of_Intent__c>  getLOIs() {
     String UserId = UserInfo.getUserId();
    return[select Name, Candidate_Name__c, Status__c, Status_Date__c from TQB_Letter_of_Intent__c where Candidates_1st_Line_Supervisor_Name__c = :UserId];
    }
    
    @AuraEnabled
    public static List<TQB_Candidate_Package__c>  getCPs() {
     String UserId = UserInfo.getUserId();
    return [select Name, Candidate_Name__c, Status__c, Status_Date__c from TQB_Candidate_Package__c where Candidates_1st_Line_Supervisor_Name__c = :UserId] ;    
    }

}