retrieveUnpackaged/objects/TQB_Candidate_Package__c.object
<CustomObject>
    <description>Custom object that stores the Candidate&apos;s promotion package data and related fields.</description>
    <fields>
        <fullName>Status_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Status Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Candidate Package Statuses</description>
        <inlineHelpText>Candidate Package Statuses</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Approved By 1st Line Supervisor</fullName>
                </value>
                <value>
                    <fullName>Approved By 2nd Line Supervisor</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TQB Candidate Package</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Candidate Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TQB_Candidate_Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/TQBHomeProgressBarController.cls
public with sharing class TQBHomeProgressBarController {

    @AuraEnabled
    public static List<TQB_Letter_of_Intent__c>  getLetters() {        
        List<TQB_Letter_of_Intent__c> letters = [Select Id, Name, Status__c, Status_Date__c FROM TQB_Letter_of_Intent__c where CreatedById = :UserInfo.getUserId() order by Name];                
        return letters ;
    }

    @AuraEnabled
    public static List<TQB_Candidate_Package__c>  getPackages() {
        List<TQB_Candidate_Package__c> packages = [Select Id, Name, Status__c, Status_Date__c FROM TQB_Candidate_Package__c where CreatedById = :UserInfo.getUserId() order by Name];
        return packages ;
    }

}